name = "workers-cloudflare-com"
account_id = "8995c0f49cdcf57eb54d2c1e52b7d2f3"
main = "./src/index.ts"
compatibility_date = "2023-09-01"
workers_dev = true
kv_namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" }, # prod
]

[vars]
SANITY_PROJECT_ID = "0s2zavz0"
SANITY_DATASET = "production"

[env.production]
workers_dev = false
route = "https://workers.cloudflare.com/playground*"
kv_namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" }, # prod
]
